### ISSUE TITLE
Quick Multi Select Function 

### ISSUE THREAD

**Issue by Jingo91** [devsharif/js-media-selector#1]
Hey,

thanks for this amazing and beautiful tool. It already helps me alot. I would love a function, where I could multi selecting the images, by making a click on one image and then shift click on the other, so all the images in between are getting selected. With this function this library would be the ultimate image selection library.

Best 
Tolga

**Comment by devsharif** [comment]
Hi,

Thank you for your suggestion, I updated the code with new feature. Now you can select multiple file using Shift+Ctrl key.
Here's the added feature. https://github.com/devsharif/js-media-selector/commit/38a58e6e4006087a9370ea97d8f330a50c86c9ad

Thank you.
Sharif Ullah

**Comment by Jingo91** [comment]
Hey,

thanks for the quick update man. I just tested it out. It works perfectly, when selecting downwards. But when selecting an image and Shift Clicking on an image on the top side, it doesnt work properly. Any idea why?

Best regards
Tolga

**Comment by devsharif** [comment]
I noticed that issue, I will solve it very soon.

Thank you for notify me.

**Comment by devsharif** [comment]
Hello @Jingo91,
The issue related to select multiple items in backward are fixed. Please check now and let me know if you find any other issue.

Thanks.

**Comment by devsharif** [comment]
After testing found that all functionality is working fine and didn't get any new report.
